### ISSUE TITLE
Output plugin 'firehose' cannot be loaded

### ISSUE THREAD

**Issue by d-baranowski** [aws/amazon-kinesis-firehose-for-fluent-bit#10]
Hi, 

Can't seem to get the firehose output working. I used the docker hub image 1.2.2
Can someone have a look? Looks like an issue with the image to me. 

Config:
```
fluent-bit.conf: |-
    [SERVICE]
        Flush          2
        Daemon         Off
        Config_Watch On
        Parsers_File   parsers.conf
        HTTP_Listen    0.0.0.0
        HTTP_Server On
        HTTP_Port      2020

    [INPUT]
        Name           tail
        Tag            kube.*
        Parser         docker
        Path           /var/log/containers/*.log
        DB             /var/log/flb_kube.db
        Mem_Buf_Limit  5MB

    [OUTPUT]
        Name   firehose
        Match  kube.*
        region eu-west-1
        delivery_stream spl-traefik-logs
```

Error:
```
log is DEPRECATED and will be removed in a future version. Use logs instead.
Output plugin 'firehose' cannot be loaded
Error: You must specify an output target. Aborting
```

**Comment by d-baranowski** [comment]
Never mind :P I was being silly. I overrode the args in spec.template.spec.command in my deamonset.yml which caused it to drop the default image -e flag. As soon as I added: 

```
spec:
      containers:
      - command:
        - /fluent-bit/bin/fluent-bit
        - -c
        - /fluent-bit/etc/fluent-bit.conf
        - -q
        - -e # this command to load the plugin
        - /fluent-bit/firehose.so
```

It worked fine
